<<<<<<< HEAD

        #################################################
        ### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
        #################################################
        # file to edit: dev_nb/006e_camvid.ipynb

from nb_005a import *
from nb_005b import *

from nb_006 import *
import fast_progress as fp
||||||| merged common ancestors
=======

        #################################################
        ### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
        #################################################
        # file to edit: dev_nb/006e_camvid.ipynb

from nb_006a import *
>>>>>>> bb9d993c2a98ee2827b06884e4f5f389dfe43ee9
