
        #################################################
        ### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
        #################################################
        # file to edit: dev_nb/006c_camvid.ipynb

from nb_006a import *
from concurrent.futures import ProcessPoolExecutor