
        #################################################
        ### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
        #################################################
        # file to edit: dev_nb/006d_imgnet.ipynb

from matplotlib import patches, patheffects

def bb_hw(a): return np.array([a[1],a[0],a[3]-a[1]+1,a[2]-a[0]+1])

def draw_outline(o, lw):
    o.set_path_effects([patheffects.Stroke(
        linewidth=lw, foreground='black'), patheffects.Normal()])

def draw_rect(ax, b, color='white'):
    patch = ax.add_patch(patches.Rectangle(b[:2], *b[2:], fill=False, edgecolor=color, lw=2))
    draw_outline(patch, 4)

def draw_text(ax, xy, txt, sz=14):
    text = ax.text(*xy, txt,
        verticalalignment='top', color='white', fontsize=sz, weight='bold')
    draw_outline(text, 1)

def show_img_annos(img, annos, lbl_to_txt=None, ax=None):
    if not ax: fig,ax = plt.subplots()
    ax.imshow(img.numpy().transpose(1,2,0))
    for anno in annos: draw_anno(ax, anno, lbl_to_txt=lbl_to_txt)

def show_img_anno(img, anno, lbl_to_txt=None, ax=None):
    if not ax: fig,ax = plt.subplots()
    ax.imshow(img.numpy().transpose(1,2,0))
    draw_anno(ax, anno, lbl_to_txt=lbl_to_txt)

def draw_anno(ax, anno, lbl_to_txt=None):
    c, bb = anno
    b = bb_hw(bb)
    draw_rect(ax, b)
    if lbl_to_txt: draw_text(ax, b[:2], lbl_to_txt[c], sz=16)