#!/usr/bin/env python

# This script signs all notebooks in the docs_src directory as trusted
# It's is used as a git post-merge hook

import nbformat.sign, sys, os
from pathlib import Path

# make sure we are under the root of the project
cur_dir = Path(".").resolve().name
if (cur_dir == "tools"): os.chdir("..")

print("Attention! Changing all notebooks under docs_src to be *trusted*", end="\r")

path = Path('docs_src')
for fname in path.glob("*.ipynb"):
    with open(fname) as f:
        nb = nbformat.read(f, as_version=4)
        if not nbformat.sign.NotebookNotary().check_signature(nb):
            nbformat.sign.NotebookNotary().sign(nb)

# clear the output
sys.stdout.write("\033[K")
