#!/usr/bin/env python

# This script signs all notebooks in the docs_src directory as trusted
# It's is used as a git post-merge hook

import nbformat.sign, sys, os
from pathlib import Path

print("Attention! Changing all notebooks under docs_src to be *trusted*")

# make sure we are under the root of the project
cur_dir = Path(".").resolve().name
if (cur_dir == "tools"): os.chdir("..")

path = Path('docs_src')
fnames = [file for file in path.glob("*.ipynb")]
for fname in fnames:
    with open(fname) as f:
        nb = nbformat.read(f, as_version=4)
        nbformat.sign.NotebookNotary().sign(nb)
print("Done")
