#!/usr/bin/env python

# This script signs all notebooks in the docs_src directory as trusted
# It's is used as a git post-merge hook

import nbformat.sign, sys, os, os.path
from pathlib import Path

# make sure we are under the root of the project
cur_dir = Path(".").resolve().name
if (cur_dir == "tools"): os.chdir("..")

print("Attention! Signing notebooks under docs_src as *trusted*", end="\r")

path = Path('docs_src')
fname_last_checked = path/".last_checked"
last_checked = os.path.getmtime(fname_last_checked) if fname_last_checked.exists() else None

for fname in path.glob("*.ipynb"):

    # speed up things by skipping the if-not-signed test if the nb hasn't changed since the last signing attempt
    if last_checked:
        last_changed = os.path.getmtime(fname)
        if last_changed < last_checked: continue

    with open(fname) as f:
        nb = nbformat.read(f, as_version=4)
        if not nbformat.sign.NotebookNotary().check_signature(nb):
            #print(f"unsigned {fname}")
            nbformat.sign.NotebookNotary().sign(nb)

fname_last_checked.touch(exist_ok=True)

# clear the output
sys.stdout.write("\033[K")
