#!/usr/bin/env python

# This script signs all notebooks in the docs_src directory as trusted
# It's is used as a git post-merge hook

import nbformat.sign, sys
from pathlib import Path

print("Attention! Changing all notebooks under docs_src to be *trusted*")
path = Path(sys.argv[1] if len(sys.argv) > 1 else 'docs_src')
fnames = [file for file in path.glob("*.ipynb")]
for fname in fnames:
    with open(fname) as f:
        nb = nbformat.read(f, as_version=4)
        nbformat.sign.NotebookNotary().sign(nb)
print("Done")

